version: 0.0
os: linux
files:
 - source: /
   destination: /root/goodearth-webapp
file_exists_behavior: OVERWRITE
hooks:
#  BeforeInstall:cccccdwd
#    - location: script/install_dependencies.sh
#      timeout: 300
#      runas: root
  AfterInstall:
    - location: postbuild.sh
      timeout: 300
      runas: root
#  ApplicationStart:
#    - location: script/start_server.sh
#      timeout: 300
runas: root