import React from "react";
//import cs from "classnames";
// import { connect } from "react-redux";
import globalStyles from "styles/global.scss";
//import bootstrapStyles from "../../../../styles/bootstrap/bootstrap-grid.scss";
import styles from "../styles.scss";
// import { Link } from "react-router-dom";
import { Props } from "../../typings";
//import { Link } from "react-router-dom";

export default class Terms extends React.Component<Props, {}> {
  constructor(props: Props) {
    super(props);
    props.setCurrentSection();
  }

  render() {
    return (
      <div className={styles.terms}>
        <h3>terms of use</h3>
        <div>
          <p>
            Welcome to Goodearth.in (“Website”). GOODEARTH and/or its affiliates
            provide website features and other products and services to you when
            you visit or shop at Goodearth.in, use GOODEARTH products or
            services, or use software provided by GOODEARTH in connection with
            any of the foregoing. GOODEARTH provides the Services subject to the
            following conditions. This user agreement (“Terms and Conditions” or
            “T&amp;C” or “Terms” or “Agreement”) is between you (“you” or “End
            User” or “your” or “Buyer” or “Customer” or “Registered User”) and
            GOODEARTH (“Company” or “us” or “we” or “Goodearth.in”). This
            document is an electronic record in terms of Information Technology
            Act, 2000 and rules there under as applicable and the amended
            provisions pertaining to electronic records in various statutes as
            amended by the Information Technology Act, 2000. This electronic
            record is generated by a computer system and does not require any
            physical or digital signatures .Not withstanding anything contained
            or said in any other document, if there is a conflict between the
            terms mentioned herein below and any other document, the terms
            contained in the present T&amp;C shall alone prevail for the
            purposes of usage of the Site.
          </p>
        </div>
        <div className={globalStyles.voffset4}>
          <h5>INTRODUCTION</h5>
          <p>
            The domain name Goodearth.in is registered in the name of Eicher
            Goodearth Private Limited, a Company registered under Companies Act
            1956, whereas pursuant to demerger order dated 15th Dec 2017 issued
            by NCLT Mumbai Bench, “Goodearth Business Undertaking of Eicher
            Goodearth Private Limited” stands transferred to and vested in
            Goodearth Design Studio Private Limited which is a registered
            company under the Companies Act, 2013 having registered office s at
            2, Raghuvanshi Mills Compound, 11-12, Senapati Bapat Marg, Lower
            Parel Mumbai City, Maharashtra, India- 400 013.
          </p>
        </div>
        <div className={globalStyles.voffset4}>
          <h5>RIGHT TO CHANGE</h5>
          <p>
            Good Earth reserves the sole right to update or modify these Terms
            and Conditions at any time without prior notice. For this reason, we
            encourage you to review these Terms and Conditions every time you
            purchase products from us or use our Web Site.
          </p>
        </div>
        <div className={globalStyles.voffset4}>
          <h5>PRIVACY</h5>
          <p>
            We view protection of your privacy as a very important principle. We
            understand clearly that You and Your Personal Information is one of
            our most important assets. We store and process Your Information
            including any sensitive financial information collected (as defined
            under the Information Technology Act, 2000), if any, on computers
            that may be protected by physical as well as reasonable
            technological security measures and procedures in accordance with
            Information Technology Act 2000 and Rules there under. If you object
            to our current Privacy Policy and your information being transferred
            or used in this way please do not use Website.
          </p>
        </div>
        <div className={globalStyles.voffset4}>
          <h5>ELECTRONIC COMMUNICATIONS</h5>
          <p>
            When you use any of our Services, or send e-mails to us, you are
            communicating with us electronically. You by using our services
            consent to receive communications from us electronically. We will
            communicate with you by e-mail or by posting notices on this site or
            through other Services. You agree that all agreements, notices,
            disclosures and other communications that we provide to you
            electronically satisfy any legal requirement that such
            communications be in writing. The legal requirements would be
            inconformity with the Indian Information Technology Act, 2000 and
            rules there under as applicable and the amended provisions
            pertaining to electronic records in various statutes as amended by
            the Information Technology Act, 2000.
          </p>
        </div>
        <div className={globalStyles.voffset4}>
          <h5>INTELLECTUAL PROPERTY RIGHTS</h5>
          <p>
            Unless otherwise indicated or anything contained to the contrary or
            any proprietary material owned by a third party and so expressly
            mentioned, GOODEARTH owns all Intellectual Property Rights to and
            into the Website, including, without limitation, any and all rights,
            title and interest in and to copyright, related rights, patents,
            utility models, trademarks, trade names, service marks, designs,
            know-how, trade secrets and inventions (whether patentable or not),
            goodwill, source code, meta tags, databases, text, content,
            graphics, icons, and hyperlinks. You acknowledge and agree that you
            shall not use, reproduce or distribute any content from the Website
            belonging to GOODEARTH without obtaining authorization from it.
          </p>
          <p>
            User shall not upload post or otherwise make available on the Site
            any material protected by copyright, trademark or other proprietary
            right without the express permission of the owner of the copyright,
            trademark or other proprietary right. GOODEARTH does not have any
            express burden or responsibility to provide the Users with
            indications, markings or anything else that may aid the User in
            determining whether the material in question is copyrighted or
            trademarked. User shall be solely liable for any damage resulting
            from any infringement of copyrights, trademarks, proprietary rights
            or any other harm resulting from such a submission. By submitting
            material to any public area of the Site, User warrants that the
            owner of such material has expressly granted GOODEARTH the
            royalty-free, perpetual, irrevocable, non-exclusive right and
            license to use, reproduce, modify, adapt, publish, translate and
            distribute such material (in whole or in part) worldwide and/or to
            incorporate it in other works in any form, media or technology now
            known or hereafter developed for the full term of any copyright that
            may exist in such material. User also permits any other end user to
            access, view, store or reproduce the material for that end user’s
            personal use. User hereby grants GOODEARTH, the right to edit, copy,
            publish and distribute any material made available on the Site by
            the User. The foregoing provisions of Section 25 apply equally to
            and are for the benefit of GOODEARTH, its subsidiaries, affiliates
            and its third party content providers and licensors and each shall
            have the right to assert and enforce such provisions directly or on
            its own behalf.
          </p>
        </div>
        <div className={globalStyles.voffset4}>
          <h5>TRADEMARKS</h5>
          <p>
            The Site contain copyrighted material, trademarks and other
            proprietary information, including, but not limited to, text,
            software, photos, video, graphics, music, sound, and the entire
            contents of GOODEARTH protected by copyright as a collective work
            under the applicable copyright laws. GOODEARTH owns a copyright in
            the selection, coordination, arrangement and enhancement of such
            content, as well as in the content original to it. Users may not
            modify, publish, transmit, participate in the transfer or sale,
            create derivative works, or in any way exploit, any of the content,
            in whole or in part. Users may download / print / save copyrighted
            material for the User’s personal use only. Except as otherwisea
            expressly stated under copyright law, no copying, redistribution,
            retransmission, publication or commercial exploitation of downloaded
            material without the express permission of GOODEARTH and the
            copyright owner is permitted.
          </p>
          <p>
            If copying, redistribution or publication of copyrighted material is
            permitted, no changes in or deletion of author attribution,
            trademark legend or copyright notice shall be made. The User
            acknowledges that he/she/it does not acquire any ownership rights by
            downloading copyrighted material. Trademarks that are located within
            or on the Site or a website otherwise owned or operated in
            conjunction with GOODEARTH shall not be deemed to be in the public
            domain but rather the exclusive property of GOODEARTH, unless such
            site is under license from the trademark owner thereof in which case
            such license is for the exclusive benefit and use of GOODEARTH,
            unless otherwise stated.
          </p>
        </div>
        <div className={globalStyles.voffset4}>
          <h5>INTELLECTUAL PROPERTY RIGHTS COMPLAINTS</h5>
          <p>
            Good Earth respects the intellectual property of others. If you
            believe that your work has been copied in a way that constitutes any
            Intellectual Property Right infringement, please address a complaint
            to the ‘Customer Care’ by way of an email as provided herein below.
          </p>
        </div>
        <div className={globalStyles.voffset4}>
          <h5>USER RESPONSIBILITY AND REGISTRATION OBLIGATIONS</h5>
          <p>
            If you use the Website as Registered User, you agree that you are
            competent to contract within the meaning of the Indian Contract Act,
            1872. GOODEARTH reserves the right to terminate your membership and
            refuse to provide you with access to the Website if it is brought to
            its notice or if it is discovered that you are under the age of 18
            years. You are solely responsible for maintaining the
            confidentiality of your User ID and Password. You are responsible
            for all activities that occur under your User ID and Password. You
            agree, inter-alia, to provide true, accurate, current and complete
            information about yourself as prompted by Website registration form
            or provided by You as a Visitor or user of a third party site
            through which You access the Website. If you provide any information
            that is untrue, inaccurate, not current or incomplete or we have
            reasonable grounds to suspect that such information is untrue,
            inaccurate, not current or incomplete, or not in accordance with the
            User Agreement, GOODEARTH has the right to indefinitely suspend or
            terminate or block access of your membership with the Website and
            refuse to provide you with access to the Website.
          </p>
          <p>
            As a condition of purchase, the Site requires your permission to
            send you administrative and promotional emails. We will send you
            information regarding your account activity and purchases, as well
            as updates about our products and promotional offers. You can
            opt-out of our promotional emails anytime by clicking the
            unsubscribe link at the bottom of any of our email correspondences.
            Please see our Privacy Policy for details. The offers made in any
            promotional messages sent via emails/SMS/MMS shall be subject to
            change at the sole discretion of GOODEARTH and GOODEARTH owes no
            responsibility to provide you any information regarding such change.
          </p>
          <p>
            You undertake not to host, display, upload, modify, publish,
            transmit, update or share any information that is contained on the
            website that:
          </p>
          <p>
            belongs to another person and to which you does not have any right
            to; is grossly harmful, harassing, blasphemous; defamatory, obscene,
            pornographic, paedophilic, libellous, invasive of another’s privacy,
            hateful, or racially, ethnically objectionable, disparaging,
            relating or encouraging money laundering or gambling, or otherwise
            unlawful in any manner whatever; harm minors in any way; infringes
            any patent, trademark, copyright or other proprietary rights;
            violates any law for the time being in force; deceives or misleads
            the addressee about the origin of such messages or communicates any
            information which is grossly offensive or menacing in nature;
            impersonate another person; contains software viruses or any other
            computer code, files or programs designed to interrupt, destroy or
            limit the functionality of any computer resource; threatens the
            unity, integrity, defence, security or sovereignty of India,
            friendly relations with foreign states, or or public order or causes
            incitement to the commission of any cognisable offence or prevents
            investigation of any offence or is insulting any other nation. That
            in case it is found that you are in violation of these express
            conditions, you shall be solely responsible and shall face all legal
            consequences of the same by yourself and that GOODEARTH shall in no
            manner be held responsible for the same
          </p>
          <p>
            That in case it is found that you are in violation of these express
            conditions, you shall be solely responsible and shall face all legal
            consequences of the same by yourself and that GOODEARTH shall in no
            manner be held responsible for the same.
          </p>
          <p>
            <b>Goods listed in this invoice are not meant for resale.</b>
          </p>
        </div>
        <div className={globalStyles.voffset4}>
          <h5>BILLING</h5>
          <p>
            The price of our merchandise as mentioned on Goodearth.in is the
            Maximum Retail Price (MRP) for the said product. Such MRP shall be
            inclusive of all local taxes as are applicable in India. Additional
            applicable taxes may be charged depending upon the destination where
            the order has to be shipped to. The tax rate applied and charged
            upon the order shall include combined tax rate for both state and
            local tax rates in accordance with the address where the order is
            being shipped. GOODEARTH reserves the right to collect taxes and/or
            such other levy/ duty/ surcharge that it may have to incur in
            addition to the normal taxes it may have to pay. We may also charge
            Delivery Charges which may include postal charges/ shipment charges
            etc. that may be applicable for your country.
          </p>
        </div>
        <div className={globalStyles.voffset4}>
          <h5 id="giftcardpolicy">GIFT CARD &amp; CREDIT NOTE POLICY</h5>
          <ul>
            <li>
              Gift Cards bought on our website will be sent via email. Physical
              copy of Gift Cards bought online will not be sent separately.
            </li>
            <li>
              Gift Cards bought in INR currency in shop or on our web boutique
              can be redeemed on the website and across all shops, pan India.
            </li>
            <li>
              Gift Cards can also be bought in USD and GBP currency on web
              boutique. These Gift Cards can only be redeemed on the web
              boutique and not in shops.
            </li>
            <li>
              Gift Cards cannot be used towards buying additional Gift Cards and
              cannot be redeemed for cash or credit voucher/credit note.
            </li>
            <li>
              Gift Cards cannot be purchased using credit voucher/credit note
              issued either by shops or on our web boutique
            </li>
            <li>
              Gift Cards can only be redeemed in the same currency in which they
              are bought (i.e. You can only redeem USD or GBP Gift Card when
              shipping outside India and INR Gift Card when shipping within
              India).
            </li>
            <li>
              Gift Card value can be partially redeemed in multiple
              transactions, on both our web boutique and across all shops, pan
              India, using the same code.
            </li>
            <li>
              In case of order value exceeding the Gift Card amount, the
              outstanding balance must be paid by Debit Card/Credit Card/Net
              Banking or PayPal (for international transactions).
            </li>
            <li>
              Credit Notes are only issued in Good Earth stores. These however
              can be redeemed across all our stores pan India as well as on our
              web boutique.
            </li>
            <li>
              Multiple Gift Cards and Credit Notes CAN be applied or used in
              combination with each other in our shops and web boutique
              (online).
            </li>
            <li>
              To redeem a Credit Note against an online order(s), please sign
              into the account associated with the customer in whose name and
              email address the credit note has been issued.
            </li>
            <li>
              In shops, Credit Note can be redeemed by the customer whose name
              and email address it was issued in.
            </li>
            <li>
              With effect from April 1st, 2018, Credit Notes will be valid for 6
              months from the date of issue.
            </li>
            <li>
              Any Credit Note issued prior to April 1st, 2018, will be valid
              till 30th Sep, 2018 (i.e. 6-months from April 1st).
            </li>
            <li>
              Good Earth shall not be held responsible for any Gift Card being
              lost or stolen or redeemed without owner’s permission.
            </li>
            <li>
              With effect from January 1st, 2018, Gift Cards will be valid for 2
              years from the date of purchase.
            </li>
            <li>
              Gift Card &amp; Credit Note Policies are subject to change at any
              time without prior notice.
            </li>
          </ul>
        </div>
        <div className={globalStyles.voffset4}>
          <h5 id="howtoactivategiftcard">How to activate gift card guide</h5>
          <ul>
            <li>
              To activate your gift card, visit our web boutique and follow the
              following steps.
            </li>
            <li>
              Under the Profile tab on the header select ‘Activate Gift Card’
              from the drop-down menu. In case you are already signed in,
              information such as your name, mobile number or email ID will auto
              populate the form in the activate your gift card window. In case,
              you are not logged in fill in your first and last name in the
              input fields provided.
            </li>
            <li>
              Fill in your gift card number in the input box provided and select
              either the email address or mobile number radio buttons to choose
              the method you would like to receive your OTP via. Next, select
              the agree to terms box at the bottom of the page, and then press
              the ‘Send OTP’ button.
            </li>
            <li>
              *Please note that receiving an OTP via SMS is only applicable for
              domestic (pan Indian) phone numbers. For international numbers,
              please select the send OTP via email option.
            </li>
            <li>
              Once you receive your OTP, enter the number in the input space
              provided on the next page. Then, click on the ‘Activate Gift Card’
              tab at the bottom of the screen. In case you did not receive your
              OTP, click on the ‘Resend OTP’ link to resend the OTP.
            </li>
            <li>
              Once you have successfully submitted your OTP, a window informing
              you that your gift card is now activated will appear with details
              such as date of issue and of expiry. The window will also show you
              the available balance on the gift card.
            </li>
            <li>
              *Please note: validity will be calculated from date of purchase
              not from date of activation.
            </li>
          </ul>
        </div>
        <div className={globalStyles.voffset4}>
          <h5 id="bridalregistryterms">
            Good Earth Registry T&amp;C<span>s</span>
          </h5>
          <ul>
            <li>
              Your Good Earth Registry is online-based and is valid solely on
              our web boutique.
            </li>
            <li>
              In order to create your registry, you must be signed in to your
              Good Earth account.
            </li>
            <li>
              You can only create one active registry at a time, either a
              wedding registry or a special occasion registry.
            </li>
            <li>
              You can make changes to the name of the registry, registrant and
              co-registrant at any time.
            </li>
            <li>
              Once submitted, the email address provided by you cannot be
              changed.
            </li>
            <li>
              Please note that a change of address to another country may result
              in a change of pricing of the products in your registry catalogue.
            </li>
            <li>
              Once your Good Earth Registry is created, it cannot be deleted.
              However, you can make changes to the date and product quantities.
            </li>
            <li>
              Please note that once a single quantity of the desired product
              from your Good Earth Registry is purchased, you will not be able
              to delete the purchased item. However, items can be deleted before
              they are purchased.
            </li>
            <li>
              To track how many items have been purchased, discarded or
              requested, please visit your dashboard.
            </li>
            <li>
              Gift cards cannot be added to the Good Earth Registry, but can be
              redeemed against registry orders.
            </li>
            <li>
              Your Good Earth Registry is valid during annual sales and
              promotional events.
            </li>
            <li>
              You can share your Good Earth Registry with friends and family via
              whatsapp (on mobile) and email by copy-pasting the link.
            </li>
            <li>
              For any questions or order enquiries that you may have, please
              reach out to us on&nbsp;
              <a href="mailto:customercare@goodearth.in">
                customercare@goodearth.in
              </a>
              .
            </li>
          </ul>
        </div>
        <div className={globalStyles.voffset4}>
          <h5>CATALOGUE PRICING</h5>
          <ul>
            <li>
              By changing the country, you will be charged according to the
              price list associated with that country and NOT by any conversion
              rate.
            </li>
            <li>
              Our international catalogues are priced in Indian Rupees for
              Indian residents, British pounds for UK residents and US dollars
              for all other international customers.
            </li>
            <li>
              Due to import/trade restrictions, certain products might not be
              available for delivery in your chosen country.
            </li>
          </ul>
        </div>
        <div className={globalStyles.voffset4}>
          <h5>ORDER CANCELLATION BY GOODEARTH</h5>
          <p>
            Due to unavoidable circumstances there may be times when certain
            orders having been validly placed may not be processed or capable of
            being dispatched. GOODEARTH reserves the exclusive right to refuse
            or cancel any order for any reason. Some situations that may result
            in your order being cancelled shall include limitations on
            quantities available for purchase, inaccuracies or errors in product
            or pricing information, problems identified by our credit and fraud
            avoidance department or any defect regarding the quality of the
            product. We may also require additional verifications or information
            before accepting any order. We will contact you if all or any
            portion of your order is cancelled or if additional information is
            required to accept your order. If your order is cancelled after your
            credit card/ debit card/ any other mode of payment has been charged,
            the said amount will be reversed into your Account/ as the case may
            be to the source of the payment within a period of 30 working days.
            Any type of voucher used in these orders shall be returned and made
            available to the user in case of cancellation by GOODEARTH.
          </p>
        </div>
        <div className={globalStyles.voffset4}>
          <h5>SHIPPING &amp; PROCESSING FEE</h5>
          <p>
            Our shipping and processing charges are intended to compensate
            GOODEARTH for the cost of processing your order, handling and
            packing the products you purchase and delivering them to you. For
            further information please refer to our Shipping &amp; Payment
            Policy.
          </p>
        </div>
        <div className={globalStyles.voffset4}>
          <h5>PAYMENT</h5>
          <p>
            While availing any of the payment method/s offered by us, we are not
            responsible or take no liability ofwhatsoever nature in respect of
            any loss or damage arising directly or indirectly to you including
            but not limited to the following: (a) lack of authorization for any
            transaction/s; (b) or exceeding the preset limit mutually agreed by
            you and between your “Bank/s”; (c) or any payment issues arising out
            of the transaction; (d) or decline of transaction for any other
            reason/s.
          </p>
          <p>
            All payments made against the purchases/services on Goodearth.in by
            you shall be as against the MRP displayed on the website and shall
            be in terms and conditions of the third party Online Payment Gateway
            Services as adopted and applicable to your transaction as approved
            by GOODEARTH. Before shipping your order to you, we may request you
            to provide supporting documents (including but not limited to Govt.
            issued ID and address proof) to establish the ownership of the
            payment instrument used by you for your purchase. This is done so as
            to ensure a safe and a fool proof online shopping environment to our
            users.
          </p>
          <p>
            GOODEARTH may employ PaisaPay, PayPal and such other third party
            facilities, for Payments on the Website. Such payments can be made
            through the electronic or through Cash on delivery transactions, as
            may be permitted by GOODEARTH which shall be at its sole discretion.
            Use of such third party services will be governed by their User
            Agreement, Seller Terms, Conditions and other rules and policies as
            may be required and applicable for your nature of activities.
          </p>
        </div>
        <div className={globalStyles.voffset4}>
          <h5>DELIVERY</h5>
          <p>
            GOODEARTH endeavors but does not guarantee delivery of products in
            the stipulated time period as mentioned on the purchase of the
            product. In no manner can the contract be repudiated if GOODEARTH
            fails to deliver any one or more products in the stipulated time
            frame. However, if you fail to take the delivery of the goods,
            GOODEARTH may at its discretion charge you for additional shipping
            cost.
          </p>
        </div>
        <div className={globalStyles.voffset4}>
          <h5>LOSS IN TRANSIT</h5>
          <p>
            GOODEARTH endeavors but does not guarantee delivery of products in
            the stipulated time period as mentioned on the purchase of the
            product. In no manner can the contract be repudiated if GOODEARTH
            fails to deliver any one or more products in the stipulated time
            frame. However, if you fail to take the delivery of the goods,
            GOODEARTH may at its discretion charge you for additional shipping
            cost.
          </p>
        </div>
        <div className={globalStyles.voffset4}>
          <h5>REFUNDS &amp; RETURNS</h5>
          <p>
            GOODEARTH shall make all endeavors to deliver defect free products
            to the purchasers. GOODEARTH does not take title to any returned
            items purchased by the user unless the item is received by
            GOODEARTH. Any item purchased on our website does not qualify for
            any return unless the product delivered is damaged or has
            manufacturing defects. The defective and/or damaged goods so
            received shall be communicated to GOODEARTH within 48 hours of its
            receipt. Any communication received after 48 hours of delivery shall
            not qualify for return unless expressly covered by the product
            warranty even in case the said product has been wrongly delivered.
          </p>
          <p>
            GOODEARTH holds the sole discretion to determine whether a refund
            can be issued. For further information please read our Returns &amp;
            Exchanges Policy.
          </p>
        </div>
        <div className={globalStyles.voffset4}>
          <h5>PRODUCT DESCRIPTIONS</h5>
          <p>
            Products displayed on GOODEARTH attempts to be as accurate as
            possible. However, GOODEARTH does not warrant that product
            descriptions or other content is accurate, complete, reliable,
            current, or error-free. If a product offered by GOODEARTH is not as
            described, your sole remedy is to contact GOODEARTH within 48 hours
            of receipt and GOODEARTH reserves the right to provide a solution as
            per its discretion. GOODEARTH is not liable to issue any refunds or
            allow exchanges and/or returns as a matter of policy.
          </p>
        </div>
        <div className={globalStyles.voffset4}>
          <h5>PRODUCT COMPLIANCE</h5>
          <p>
            Products displayed/ sold on the GOODEARTH website are manufactured/
            procured as per the applicable Local Laws of India and are in
            conformity with the required Indian industry standards.
          </p>
        </div>
        <div className={globalStyles.voffset4}>
          <h5>PRODUCT PRICING DISCLAIMER</h5>
          <p>
            The prices displayed on our website may differ from prices that are
            available in stores. Further the prices displayed in our catalogs
            are quotes which may vary from country to country for the same
            product. Prices shown on the website both for India and in other
            International Countries are subject to change without prior notice.
            These prices only reflect the MRP and do not include shipping and
            taxes which may be extra as applicable.
          </p>
        </div>
        <div className={globalStyles.voffset4}>
          <h5>INACCURACY DISCLAIMER</h5>
          <p>
            From time to time there may be information on our Website or in our
            catalog that may contain typographical errors, inaccuracies, or
            omissions that may relate to product descriptions, pricing, and
            availability. GOODEARTH reserves the right to correct any errors,
            inaccuracies or omissions and to change or update information at any
            time without prior notice.
          </p>
        </div>
        <div className={globalStyles.voffset4}>
          <h5>WARRANTIES &amp; LIABILITY</h5>
          <p>
            All information, content, materials, products (including software)
            and other services included on or otherwise made available to you by
            GOODEARTH are provided on an AS IS and AS AVAILABLE basis, unless
            otherwise specified in writing. GOODEARTH makes no representations
            or warranties of any kind, express or implied, as to the operation
            of the services, or the information, content, materials, products
            (including software) or other services included on or otherwise made
            available to you through GOODEARTH, unless otherwise specified in
            writing. You expressly agree that your use of the website is at your
            sole risk.
          </p>
          <p>
            GOODEARTH does not warrant that this Website will be constantly
            available, or available at all or that any information on this
            Website is complete, true, accurate or non-misleading.
          </p>
          <p>
            We will not be liable to You in any way or in relation to the
            Contents of, or use of, or otherwise in connection with, the
            Website. You acknowledge, by your use of this Website, that your use
            of this Website is at your sole risk, that you assume full
            responsibility for all risks associated with all necessary servicing
            or repairs of any equipment you use in connection with your use of
            this Website, and that GOODEARTH shall not be liable for any damages
            of any kind related to your use of this Website.
          </p>
          <p>
            Though GOODEARTH shall make all endeavor to protect its websites
            from any viruses or other illegal use of its website. However we do
            not warrant that this site; information, Content, materials, product
            (including software) or services included on or otherwise made
            available to You through the Website; its servers; or electronic
            communication sent from us are free of viruses or other harmful
            components. Nothing on Website constitutes, or is meant to
            constitute, advice of any kind.
          </p>
          <p>
            All the Products sold on Website shall be solely governed by the
            Indian Laws. In the event we are unable to deliver such Products due
            to implications of different territorial laws, we will return or
            will give credit for the amount (if any) received in advance by us
            from the sale of such Product that could not be delivered to You. It
            is YOUR responsibility to ensure that the products purchased on this
            website is not restricted in your territory. GOODEARTH shall not be
            responsible for any non-compliance with regard to the local laws of
            that territory for any product available on this website.
          </p>
          <p>
            GOODEARTH will not be liable for any damages of any kind arising
            from the use of any service, or from any information, content,
            materials, products (including software) or other services included
            on or otherwise made available to you through the website,
            including, but not limited to direct, indirect, incidental,
            punitive, and consequential damages, unless otherwise specified in
            writing.
          </p>
        </div>
        <div className={globalStyles.voffset4}>
          <h5>INDEMNITY</h5>
          <p>
            You agree to indemnify and shall not hold GOODEARTH (and its
            officers, directors, agents, subsidiaries, affiliates, joint
            ventures, and employees) for any claim or demand, including but not
            limited to reasonable attorneys’ fees, or arising out of or related
            to your breach of this T&amp;C, or your violation of any law or the
            rights of a third party or any damage to life and/or property caused
            by the products delivered.
          </p>
        </div>
        <div className={globalStyles.voffset4}>
          <h5>BREACH</h5>
          <p>
            In the event you are found to be in breach of the Terms of Use or
            Privacy Policy or other rules and policies or if we are unable to
            verify or authenticate any information you provide or if it is
            believed that your actions may cause legal liability for you, other
            users or us, without limiting to the present, without prior notice
            immediately limit your activity, remove your information,
            temporarily/indefinitely suspend or terminate or block your
            membership, and/or refuse to provide you with access to this
            Website. Any user that has been suspended or blocked may not
            register or attempt to register with us or use the Website in any
            manner whatsoever until such time that such user is reinstated by
            us.
          </p>
          <p>
            Notwithstanding the foregoing, if you breach the Terms of Use or
            Privacy Policy or other rules and policies, we reserve the right to
            recover any amounts due and owing by you to us and to take strict
            legal action including but not limited to a referral to the
            appropriate police or other authorities for initiating criminal or
            other proceedings against you.
          </p>
          <p>
            Any breach of any applicable local laws of that territory shall also
            result in, without prior notice immediately limit your activity,
            remove your information, temporarily/indefinitely suspend or
            terminate or block your membership, and/or refuse to provide you
            with access to this Website.
          </p>
        </div>
        <div className={globalStyles.voffset4}>
          <h5>SEVERABILITY</h5>
          <p>
            We reserve the right to make changes to our site, policies, Service
            Terms, and these Conditions of Use at any time. If any of these
            conditions shall be deemed invalid, void, or for any reason
            unenforceable, that condition shall be deemed severable and shall
            not affect the validity and enforceability of any remaining
            condition.
          </p>
        </div>
        <div className={globalStyles.voffset4}>
          <h5>WAIVER</h5>
          <p>
            The failure by GOODEARTH to enforce at any time or for any period
            any one or more of the terms or conditions of the Agreement shall
            not be a waiver by GOODEARTH of them or of the right any time
            subsequent to enforce all Terms and Conditions of this agreement.
          </p>
        </div>
        <div className={globalStyles.voffset4}>
          <h5>FORCE MAJEURE</h5>
          <p>
            Failure on the part of GOODEARTH to perform any of its obligations
            and the non furnishing of the Service), shall not entitle you to
            raise any claim against GOODEARTH or be a breach hereunder to the
            extent that such failure arises from an event of Force Majeure. If
            through force Majeure the fulfillment by either party of any
            obligation set forth in this Agreement will be delayed, the period
            of such delay will not be counted on in computing periods prescribed
            by this Agreement. Force Majeure will include any war, civil
            commotion, strike, governmental action, lockout, accident, epidemic
            or any other event of any nature or kind whatsoever beyond the
            control of GOODEARTH that directly or indirectly hinders or prevents
            GOODEARTH from commencing or proceeding with consummation of the
            transactions contemplated hereby. You expressly agree that lack of
            funds shall not in any event constitute or be considered an event of
            Force Majeure.
          </p>
        </div>
        <div className={globalStyles.voffset4}>
          <h5>DISPUTE RESOLUTION</h5>
          <p>
            This agreement shall be construed and the legal relations between
            YOU and GOODEARTH hereto shall be determined and governed according
            to the laws of India. If any dispute arises between You and
            GOODEARTH regarding Your use of the Website or Your dealing with
            GOODEARTH in relation to any activity on the Website, in connection
            with the validity, interpretation, implementation or breach of any
            provision of the Terms &amp; Conditions and/or Privacy Policy
            including but not limited to the rules and policies contained
            herein, the dispute shall be subject to the exclusive jurisdiction
            to the Courts of New Delhi.
          </p>
          <p>
            Your obligations to pay the Payment Fees shall not be suspended
            during the pendency of such proceedings.
          </p>
        </div>
        <div className={globalStyles.voffset4}>
          <h5>GRIEVANCE</h5>
          <p>
            Any grievances you have by way of use of the website cab be
            addressed to the ‘Customer Care’ by way of email to&nbsp;
            <a href="mailto:customercare@goodearth.in">
              customercare@goodearth.in
            </a>
          </p>
          <p>
            The ‘Customer Care’ shall thereafter consider the same and provide a
            response within one month of the date of such complaint/ grievance.
          </p>
        </div>
        <div className={globalStyles.voffset4}>
          <h5>GOVERNING LAW</h5>
          <p>
            These Terms and Conditions or the documents of third party payment
            channels shall be governed and construed in accordance with the laws
            of India.
          </p>
          <p>
            This document is an electronic record in terms of Information
            Technology Act, 2000 and the amended provisions pertaining to
            electronic records in various statutes as amended by the Information
            Technology Act, 2000. This electronic record is generated by a
            computer system and does not require any physical or digital
            signatures.
          </p>
        </div>
      </div>
    );
  }
}
