const list = [
  "Angola",
  "Antigua and Barbuda",
  "Aruba",
  "Ascension island",
  "Bahamas",
  "Belize",
  "Benin",
  "Botswana",
  "Bolivia",
  "Bonaire, Sint Eustatius and Saba",
  "Burkina Faso",
  "Burundi",
  "Cameroon",
  "Central African Republic",
  "Comoros",
  "Congo",
  "Congo the Democratic Republic of the",
  "Cook Islands",
  "Cote d’Ivoire",
  "Curaçao",
  "Djibouti",
  "Dominica",
  "East Timor",
  "Equatorial Guinea",
  "Eritrea",
  "Fiji",
  "French Southern Territories",
  "Gambia",
  "Gamon",
  "Ghana",
  "Grenada",
  "Guyana",
  "Heard and McDonald Islands",
  "Hong Kong",
  "Kiribati",
  "Libya",
  "Macau",
  "Malawi",
  "Mali",
  "Mauritania",
  "Nauru",
  "Netherlands Antilles",
  "Niue",
  "North Korea",
  "Qatar",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Sao Tome and Principe",
  "Seychelles",
  "Sierra Leone",
  "Solomon Islands",
  "Suriname",
  "Syria",
  "Timor-Leste",
  "Togo",
  "Tokelau",
  "Tonga",
  "Tuvalu",
  "Uganda",
  "United Arab Emirates",
  "Vanuatu",
  "Yemen",
  "Zimbabwe"
];

export default list;
