export type PageMeta = {
  keywords: string;
  description: string;
  title: string;
  ogTitle: string;
  ogUrl: string;
  ogImage: string;
  ogImageHeight: string;
  ogImageWidth: string;
  ogDescription: string;
  ogSiteName: string;
  ogType: string;
  isChat: boolean;
  templateType: string;
  productClass: string;
  twitterCard: string;
  twitterTitle: string;
  twitterUrl: string;
  twitterDescription: string;
  twitterImage: string;
  twitterDomain: string;
  twitterCreator: string;
  twitterSite: string;
};
